# GR00T closed-loop policy config for G1 simple pick and place task
model_path: /home/ray/models/simple-pick-and-place-merged
language_instruction: "Pick up the brown box and place it on the green target square."
# Action horizon is the number of actions predicted by the policy per inference rollout
action_horizon: 16
embodiment_tag: new_embodiment
video_backend: decord
data_config: unitree_g1_fixed_base

policy_joints_config_path: /home/ray/IsaacLab-Arena/isaaclab_arena_gr00t/config/g1/gr00t_43dof_joint_space.yaml
action_joints_config_path: /home/ray/IsaacLab-Arena/isaaclab_arena_gr00t/config/g1/43dof_joint_space.yaml
state_joints_config_path: /home/ray/IsaacLab-Arena/isaaclab_arena_gr00t/config/g1/43dof_joint_space.yaml

# Action chunk length is the number of actions executed per inference rollout
action_chunk_length: 16
pov_cam_name_sim: "robot_head_cam_rgb"

task_mode_name: g1_fixed_base_manipulation
